#!/bin/bash

python MCvsNM_32_InceptionV3_None_data0.py > MCvsNM_32_InceptionV3_None_data0_results.txt
python MCvsNM_32_InceptionV3_None_data1.py > MCvsNM_32_InceptionV3_None_data1_results.txt
python MCvsNM_32_InceptionV3_None_data2.py > MCvsNM_32_InceptionV3_None_data2_results.txt
python MCvsNM_32_InceptionV3_None_data3.py > MCvsNM_32_InceptionV3_None_data3_results.txt
python MCvsNM_32_InceptionV3_None_data4.py > MCvsNM_32_InceptionV3_None_data4_results.txt

