#!/bin/bash

python ADvsNM_32_InceptionV3_None_data0.py > ADvsNM_32_InceptionV3_None_data0_results.txt
python ADvsNM_32_InceptionV3_None_data1.py > ADvsNM_32_InceptionV3_None_data1_results.txt
python ADvsNM_32_InceptionV3_None_data2.py > ADvsNM_32_InceptionV3_None_data2_results.txt
python ADvsNM_32_InceptionV3_None_data3.py > ADvsNM_32_InceptionV3_None_data3_results.txt
python ADvsNM_32_InceptionV3_None_data4.py > ADvsNM_32_InceptionV3_None_data4_results.txt

